{% set name = "segregation" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segregation-{{ version }}.tar.gz
  sha256: 4da8dfef5aa27556161d6931fdc666c1700dd580c5d838810f1839b440826edf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - deprecation
    - geopandas >=0.9
    - joblib
    - libpysal
    - mapclassify
    - matplotlib-base
    - numba
    - numpy
    - pandas
    - pip
    - pygeos
    - pyproj >=3
    - python >=3.7
    - quilt3
    - rvlib >=0.0.5
    - scikit-learn >=0.21.3
    - scipy
    - seaborn
    - tqdm

test:
  imports:
    - segregation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Segregation Measures Framework in PySAL

  description: |
    The PySAL segregation module allow users to estimate several segregation measures and perform 
    inference for single measures and comparative inference in a concise way.
  doc_url: http://segregation.readthedocs.io/
  dev_url: https://github.com/pysal/segregation

extra:
  recipe-maintainers:
    - renanxcortes
    - sjsrey
    - knaaptime
    - ocefpaf
