{% set version = "2.0.0" %}

package:
  name: segregation
  version: {{ version }}

source:
  url: https://github.com/pysal/segregation/archive/v{{ version }}.tar.gz
  sha256: 1a3054007527e53a90e3230f0af0a85909a1a5e3a5d18f9af7ffb731ec7f8616

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pandas
    - geopandas
    - matplotlib-base
    - scikit-learn
    - seaborn
    - numpy
    - scipy
    - libpysal
    - tqdm
    # FIXME: workaround until we rebuild gdal
    - zstd

test:
  imports:
    - segregation

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Segregation Measures Framework in PySAL

  description: |
    The PySAL segregation module allow users to estimate several segregation measures and perform 
    inference for single measures and comparative inference in a concise way.
  doc_url: http://segregation.readthedocs.io/
  dev_url: https://github.com/pysal/segregation

extra:
  recipe-maintainers:
    - renanxcortes
    - sjsrey
    - knaaptime
